### ISSUE TITLE
Week 1 hacks

### ISSUE THREAD

**Issue by Ryanrob327** [Ryanrob327/csp#3]
[Custom homepage](https://ryanrob327.github.io/csp/)
[Vocab Page](https://ryanrob327.github.io/csp/vocab/)
[Python Quiz](https://ryanrob327.github.io/csp/fastpages/jupyter/python/2022/08/28/Python-Quiz.html) - extra credit
[Bash Notebook](https://ryanrob327.github.io/csp/fastpages/jupyter/bash/2022/08/25/Bash-notebook.html)
[Notes for school](https://ryanrob327.github.io/csp/markdown/2022/08/28/Class-Notes.html) - extra credit

**Comment by JoshuaW03628** [comment]
I would give Ryan a 3.0!!!. Everything is up to standard or better with extra credit slotted in different areas well done.!!

**Comment by CodeingChris** [comment]
I would give you a 3.0, all the effort and dedication was put into all sections of work. It met all and more expectations, great job! - Chris A.

**Comment by EliGilmour** [comment]
I would give Ryan a 3 out of 3 because Ryan met all the requirements for this assignment and he went above and beyond with his custom homepage. Everything is organized and up and running.
