### ISSUE TITLE
Week 2 Hacks

### ISSUE THREAD

**Issue by Ryanrob327** [Ryanrob327/csp#4]
[Python lists and dictionaries](https://ryanrob327.github.io/csp/python/week2/2022/08/30/Python_Lists.html)
[Table made with HTML](https://ryanrob327.github.io/csp/Overview/)
[My attempt to change the theme](https://ryanrob327.github.io/csp/2022/09/05/HTML-Fragments.html)
[Orginized tags](https://ryanrob327.github.io/csp/categories/)

**Comment by JoshuaW03628** [comment]
This is a good review ticket and has the possibility of exceeding a 2.7 due to the showing of understanding in the quiz. Well Done 2.7+.

**Comment by EliGilmour** [comment]
I would give Ryan a 2.7+ because he did everything that was required for this week's assignments and is a great website including the HTML fragments and I like the lists and dictionaries post a lot., but I wouldn't give him a 3 because he didn't go above and beyond on his project.

**Comment by CodeingChris** [comment]
I would give Ryan 2.7 because everything was completed and reached, and his layout is clean and easy to accsess. Great job, 2.7+!
